services:
  mc-server:
    image: mc-server
    container_name: test
    environment:
      - MC_VERSION=26.1-snapshot-7
      - MC_LOADER_VERSION=idkthisdoesnotmatterrn
      - MC_LOADER=vanilla
    restart: unless-stopped
    ports:
      - "25565:25565"
    mem_limit: 4G
    mem_reservation: 3G
    memswap_limit: 5G

# eee need to do volumes someday
# but now i dont want to keep these trashy files
