services:
  mc-server:
    image: mc-server
    container_name: test
    environment:
      - MC_VERSION=1.17.1
      - MC_LOADER_VERSION=0.18.2
      - MC_LOADER=fabric
    restart: unless-stopped
    ports:
      - "25565:25565"

# eee need to do volumes someday
# but now i dont want to keep these trashy files
